### ISSUE TITLE
C3 - C14	100nF

### ISSUE THREAD

**Issue by callimero** [Allen-Synthesis/EuroPi#176]
# Documentation Suggestion

**Describe the issue or suggestion**  
The BOM says Nanofarad Capacitor (Non-Polarised)

The schematic shows polarized caps.

**Comment by roryjamesallen** [comment]
This is because some DIYers might only have polarised caps on hand of this value, and polarised caps work just as well.

The thing is that if the schematic (and therefore PCB footprint) were non-polarised, then users with polarised caps wouldn't know which way around to place them, whereas if the footprint is polarised (as it is currently), users with non-polarised caps can just put it either way, and users with polarised caps can orient it correctly.
