### ISSUE TITLE
Are the "Discussions" gone?

### ISSUE THREAD

**Issue by callimero** [Allen-Synthesis/EuroPi#344]
Where are the discussions pages?

e.g. **https://github.com/Allen-Synthesis/EuroPi/discussions/322**

just a 404.

**Comment by chrisib** [comment]
The discussions section was closed as nobody was actively monitoring it. There were posts on there from a year ago that had never been noticed.  Most of the EuroPi discussion goes on on [Discord ](https://discord.gg/JaQwtCnBV5).

For specific issues/questions/feature requests, we prefer Github Issues, since they're easier to monitor.

**Comment by callimero** [comment]
Ahhh... Somehow the mentions from GitHub were delayed or so! 

Ok see you on discord.
